
jobs:
- name: build
  plan:
    - aggregate:
      - get: tools
      - get: repo
        trigger: true
    - task: task-build
      file: tools/tasks/build-and-upload/task.yml



resources:
- name: repo
  type: git
  source:
    uri: ((repo_url))
    branch: master
    private_key: ((github_rsa.private_key))
- name: tools
  type: git
  source:
    uri: https://github.com/warroyo/concourse-go-template.git
    branch: master