
jobs:
- name: build
  plan:
    - aggregate:
      - get: tools
      - get: repo
        trigger: true
    - task: task-build
      file: tools/tasks/build/task.yml
    - put: app-image
      params: {
        build: out
        }
- name: kubernetes-deploy-dev
  plan:
  - get: repo
  - put: kubernetes-dev
    params:
      kubectl: apply -f my-app/k8s -f my-app/k8s/production
      wait_until_ready_selector: app=myapp

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.11"

resources:
- name: repo
  type: git
  source:
    uri: ((repo_url))
    branch: master
    private_key: ((github_rsa.private_key))
- name: tools
  type: git
  source:
    uri: https://github.com/warroyo/concourse-go-template.git
    branch: master
- name: app-image
  type: docker-image
  source:
    repository: warroyo90/((app_name))
    username: ((docker_login.username))
    password: ((docker_login.password))
- name: kubernetes-dev
  type: kubernetes
  source:
    server: https://dev.clusters.warroyo.com:8443
    namespace: dev
    token: ((kube_concourse))
    certificate_authority: ((kube_concourse_ca.certificate))