
jobs:
- name: build
  plan:
    - aggregate:
      - get: tools
      - get: repo
        trigger: true
    - task: task-build
      file: tools/tasks/build/task.yml
    - put: app-image
      params: {
        build: tools/tasks/build
        }


resources:
- name: repo
  type: git
  source:
    uri: ((repo_url))
    branch: master
    private_key: ((github_rsa.private_key))
- name: tools
  type: git
  source:
    uri: https://github.com/warroyo/concourse-go-template.git
    branch: master
- name: app-image
  type: docker-image
  source:
    repository: warroyo90/debug-resource:1.0.0
    username: ((docker_login.username))
    password: ((docker_login.password))