platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11.1

inputs:
  - name: tools
  - name: repo

outputs:
- name: out

run:
  path: ./tools/tasks/build-and-upload/task.sh