platform: linux

image_resource:
  type: docker-image
  source:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.11.3

inputs:
  - name: tools
  - name: repo

outputs:
- name: out


run:
  path: ./tools/tasks/service/task.sh